title: KLoadGen - Generate performance and business-logic tests in an easy and maintainable way.
description: Built by Corunet, Kloadgen is an open-source, JMeter plugin that allows generating and injecting synthetic data into a Kafka-based, event architecture.
twitter:
  username: corunet
  card: summary
image: /assets/corunet-logo.svg
logo: /assets/corunet-logo.svg
# show_downloads: true
# google_analytics:
theme: jekyll-theme-tactile
